### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by ghost** [aperpen/clash-royale-client#9]
When I do 'node index' I get

clash-royale-client-master\config.js:5
    credentials: [{
    ^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

Any thoughts?

**Comment by aperpen** [comment]
A comma was missing in config.example. Fixed :+1:
